# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather-app.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeatherApp(object):
    def setupUi(self, WeatherApp):
        WeatherApp.setObjectName("WeatherApp")
        WeatherApp.resize(715, 641)
        self.gridLayout = QtWidgets.QGridLayout(WeatherApp)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(WeatherApp)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.searchParentLayoutVertical = QtWidgets.QVBoxLayout()
        self.searchParentLayoutVertical.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.searchParentLayoutVertical.setObjectName("searchParentLayoutVertical")
        self.searchLabel = QtWidgets.QLabel(self.groupBox)
        self.searchLabel.setMaximumSize(QtCore.QSize(700, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchLabel.setFont(font)
        self.searchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.searchLabel.setObjectName("searchLabel")
        self.searchParentLayoutVertical.addWidget(self.searchLabel)
        self.searchChildLayoutHorizontal = QtWidgets.QHBoxLayout()
        self.searchChildLayoutHorizontal.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.searchChildLayoutHorizontal.setContentsMargins(-1, -1, -1, 0)
        self.searchChildLayoutHorizontal.setObjectName("searchChildLayoutHorizontal")
        self.searchTextEdit = QtWidgets.QTextEdit(self.groupBox)
        self.searchTextEdit.setMaximumSize(QtCore.QSize(350, 30))
        self.searchTextEdit.setToolTip("")
        self.searchTextEdit.setObjectName("searchTextEdit")
        self.searchChildLayoutHorizontal.addWidget(self.searchTextEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.searchChildLayoutHorizontal.addItem(spacerItem)
        self.searchButton = QtWidgets.QPushButton(self.groupBox)
        self.searchButton.setEnabled(True)
        self.searchButton.setMaximumSize(QtCore.QSize(100, 20))
        self.searchButton.setObjectName("searchButton")
        self.searchChildLayoutHorizontal.addWidget(self.searchButton)
        self.searchParentLayoutVertical.addLayout(self.searchChildLayoutHorizontal)
        self.searchParentLayoutVertical.setStretch(0, 50)
        self.searchParentLayoutVertical.setStretch(1, 50)
        self.verticalLayout_6.addLayout(self.searchParentLayoutVertical)
        self.currentInformationLayoutVertical = QtWidgets.QVBoxLayout()
        self.currentInformationLayoutVertical.setContentsMargins(100, -1, 100, -1)
        self.currentInformationLayoutVertical.setObjectName("currentInformationLayoutVertical")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCity = QtWidgets.QLabel(self.groupBox)
        self.labelCity.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelCity.setFont(font)
        self.labelCity.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCity.setObjectName("labelCity")
        self.horizontalLayout_2.addWidget(self.labelCity)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelCurrentTemperature = QtWidgets.QLabel(self.groupBox)
        self.labelCurrentTemperature.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelCurrentTemperature.setFont(font)
        self.labelCurrentTemperature.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentTemperature.setObjectName("labelCurrentTemperature")
        self.horizontalLayout_2.addWidget(self.labelCurrentTemperature)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.currentInformationLayoutVertical.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.labelCurrentAdditionalInfo = QtWidgets.QLabel(self.groupBox)
        self.labelCurrentAdditionalInfo.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelCurrentAdditionalInfo.setFont(font)
        self.labelCurrentAdditionalInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentAdditionalInfo.setObjectName("labelCurrentAdditionalInfo")
        self.horizontalLayout.addWidget(self.labelCurrentAdditionalInfo)
        self.labelCurrentAdditionalInfo_2 = QtWidgets.QLabel(self.groupBox)
        self.labelCurrentAdditionalInfo_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelCurrentAdditionalInfo_2.setFont(font)
        self.labelCurrentAdditionalInfo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentAdditionalInfo_2.setObjectName("labelCurrentAdditionalInfo_2")
        self.horizontalLayout.addWidget(self.labelCurrentAdditionalInfo_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.currentInformationLayoutVertical.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.currentInformationLayoutVertical)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setMinimumSize(QtCore.QSize(670, 120))
        self.scrollArea.setMaximumSize(QtCore.QSize(670, 120))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 720, 116))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.labelTime = QtWidgets.QLabel(self.groupBox_2)
        self.labelTime.setGeometry(QtCore.QRect(20, 10, 58, 18))
        self.labelTime.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime.setObjectName("labelTime")
        self.labelImage1 = QtWidgets.QLabel(self.groupBox_2)
        self.labelImage1.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.labelImage1.setText("")
        self.labelImage1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage1.setObjectName("labelImage1")
        self.labelTime_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelTime_2.setGeometry(QtCore.QRect(20, 80, 58, 18))
        self.labelTime_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_2.setObjectName("labelTime_2")
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.labelImage1_2 = QtWidgets.QLabel(self.groupBox_3)
        self.labelImage1_2.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.labelImage1_2.setText("")
        self.labelImage1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage1_2.setObjectName("labelImage1_2")
        self.labelTime_3 = QtWidgets.QLabel(self.groupBox_3)
        self.labelTime_3.setGeometry(QtCore.QRect(20, 10, 58, 18))
        self.labelTime_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_3.setObjectName("labelTime_3")
        self.labelTime_4 = QtWidgets.QLabel(self.groupBox_3)
        self.labelTime_4.setGeometry(QtCore.QRect(20, 80, 58, 18))
        self.labelTime_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_4.setObjectName("labelTime_4")
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.labelImage1_3 = QtWidgets.QLabel(self.groupBox_4)
        self.labelImage1_3.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.labelImage1_3.setText("")
        self.labelImage1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage1_3.setObjectName("labelImage1_3")
        self.labelTime_6 = QtWidgets.QLabel(self.groupBox_4)
        self.labelTime_6.setGeometry(QtCore.QRect(20, 80, 58, 18))
        self.labelTime_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_6.setObjectName("labelTime_6")
        self.labelTime_5 = QtWidgets.QLabel(self.groupBox_4)
        self.labelTime_5.setGeometry(QtCore.QRect(20, 10, 58, 18))
        self.labelTime_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_5.setObjectName("labelTime_5")
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.labelImage1_4 = QtWidgets.QLabel(self.groupBox_5)
        self.labelImage1_4.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.labelImage1_4.setText("")
        self.labelImage1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage1_4.setObjectName("labelImage1_4")
        self.labelTime_7 = QtWidgets.QLabel(self.groupBox_5)
        self.labelTime_7.setGeometry(QtCore.QRect(20, 10, 58, 18))
        self.labelTime_7.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_7.setObjectName("labelTime_7")
        self.labelTime_8 = QtWidgets.QLabel(self.groupBox_5)
        self.labelTime_8.setGeometry(QtCore.QRect(20, 80, 58, 18))
        self.labelTime_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_8.setObjectName("labelTime_8")
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.labelImage1_5 = QtWidgets.QLabel(self.groupBox_6)
        self.labelImage1_5.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.labelImage1_5.setText("")
        self.labelImage1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage1_5.setObjectName("labelImage1_5")
        self.labelTime_10 = QtWidgets.QLabel(self.groupBox_6)
        self.labelTime_10.setGeometry(QtCore.QRect(20, 80, 58, 18))
        self.labelTime_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_10.setObjectName("labelTime_10")
        self.labelTime_9 = QtWidgets.QLabel(self.groupBox_6)
        self.labelTime_9.setGeometry(QtCore.QRect(20, 10, 58, 18))
        self.labelTime_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_9.setObjectName("labelTime_9")
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.labelImage1_6 = QtWidgets.QLabel(self.groupBox_7)
        self.labelImage1_6.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.labelImage1_6.setText("")
        self.labelImage1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage1_6.setObjectName("labelImage1_6")
        self.labelTime_12 = QtWidgets.QLabel(self.groupBox_7)
        self.labelTime_12.setGeometry(QtCore.QRect(20, 80, 58, 18))
        self.labelTime_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_12.setObjectName("labelTime_12")
        self.labelTime_11 = QtWidgets.QLabel(self.groupBox_7)
        self.labelTime_11.setGeometry(QtCore.QRect(20, 10, 58, 18))
        self.labelTime_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_11.setObjectName("labelTime_11")
        self.horizontalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_8.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.labelTime_14 = QtWidgets.QLabel(self.groupBox_8)
        self.labelTime_14.setGeometry(QtCore.QRect(20, 80, 58, 18))
        self.labelTime_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_14.setObjectName("labelTime_14")
        self.labelTime_13 = QtWidgets.QLabel(self.groupBox_8)
        self.labelTime_13.setGeometry(QtCore.QRect(20, 10, 58, 18))
        self.labelTime_13.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelTime_13.setObjectName("labelTime_13")
        self.labelImage1_7 = QtWidgets.QLabel(self.groupBox_8)
        self.labelImage1_7.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.labelImage1_7.setText("")
        self.labelImage1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage1_7.setObjectName("labelImage1_7")
        self.horizontalLayout_4.addWidget(self.groupBox_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setMinimumSize(QtCore.QSize(100, 150))
        self.widget.setMaximumSize(QtCore.QSize(700, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelDay = QtWidgets.QLabel(self.widget_2)
        self.labelDay.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDay.setObjectName("labelDay")
        self.horizontalLayout_7.addWidget(self.labelDay)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelMinTemp = QtWidgets.QLabel(self.widget_2)
        self.labelMinTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinTemp.setObjectName("labelMinTemp")
        self.horizontalLayout_8.addWidget(self.labelMinTemp)
        self.labelMaxTemp = QtWidgets.QLabel(self.widget_2)
        self.labelMaxTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaxTemp.setObjectName("labelMaxTemp")
        self.horizontalLayout_8.addWidget(self.labelMaxTemp)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelDay_2 = QtWidgets.QLabel(self.widget_5)
        self.labelDay_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDay_2.setObjectName("labelDay_2")
        self.horizontalLayout_9.addWidget(self.labelDay_2)
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelMinTemp_2 = QtWidgets.QLabel(self.widget_5)
        self.labelMinTemp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinTemp_2.setObjectName("labelMinTemp_2")
        self.horizontalLayout_10.addWidget(self.labelMinTemp_2)
        self.labelMaxTemp_2 = QtWidgets.QLabel(self.widget_5)
        self.labelMaxTemp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaxTemp_2.setObjectName("labelMaxTemp_2")
        self.horizontalLayout_10.addWidget(self.labelMaxTemp_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6.addWidget(self.widget_5)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelDay_3 = QtWidgets.QLabel(self.widget_3)
        self.labelDay_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDay_3.setObjectName("labelDay_3")
        self.horizontalLayout_11.addWidget(self.labelDay_3)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelMinTemp_3 = QtWidgets.QLabel(self.widget_3)
        self.labelMinTemp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinTemp_3.setObjectName("labelMinTemp_3")
        self.horizontalLayout_12.addWidget(self.labelMinTemp_3)
        self.labelMaxTemp_3 = QtWidgets.QLabel(self.widget_3)
        self.labelMaxTemp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaxTemp_3.setObjectName("labelMaxTemp_3")
        self.horizontalLayout_12.addWidget(self.labelMaxTemp_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6.addWidget(self.widget_3)
        self.verticalLayout_6.addWidget(self.widget)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_16.setMinimumSize(QtCore.QSize(700, 200))
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_21)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.label_10 = QtWidgets.QLabel(self.groupBox_21)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.horizontalLayout_15.addWidget(self.groupBox_21)
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_22)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox_22)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.label_12 = QtWidgets.QLabel(self.groupBox_22)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.horizontalLayout_15.addWidget(self.groupBox_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_19)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_11 = QtWidgets.QLabel(self.groupBox_19)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_13.addWidget(self.groupBox_19)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_20.setTitle("")
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_20)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_7 = QtWidgets.QLabel(self.groupBox_20)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.horizontalLayout_13.addWidget(self.groupBox_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox_18)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.label_14 = QtWidgets.QLabel(self.groupBox_18)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.horizontalLayout_14.addWidget(self.groupBox_18)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox_17)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.label_15 = QtWidgets.QLabel(self.groupBox_17)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.horizontalLayout_14.addWidget(self.groupBox_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.verticalLayout_6.addWidget(self.groupBox_16)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(WeatherApp)
        QtCore.QMetaObject.connectSlotsByName(WeatherApp)

    def retranslateUi(self, WeatherApp):
        _translate = QtCore.QCoreApplication.translate
        WeatherApp.setWindowTitle(_translate("WeatherApp", "Dialog"))
        self.searchLabel.setText(_translate("WeatherApp", "Search by the city name"))
        self.searchButton.setText(_translate("WeatherApp", "Search"))
        self.labelCity.setText(_translate("WeatherApp", "City"))
        self.labelCurrentTemperature.setText(_translate("WeatherApp", "temp"))
        self.labelCurrentAdditionalInfo.setText(_translate("WeatherApp", "Info"))
        self.labelCurrentAdditionalInfo_2.setText(_translate("WeatherApp", "img"))
        self.labelTime.setText(_translate("WeatherApp", "time"))
        self.labelTime_2.setText(_translate("WeatherApp", "temp"))
        self.labelTime_3.setText(_translate("WeatherApp", "time"))
        self.labelTime_4.setText(_translate("WeatherApp", "temp"))
        self.labelTime_6.setText(_translate("WeatherApp", "temp"))
        self.labelTime_5.setText(_translate("WeatherApp", "time"))
        self.labelTime_7.setText(_translate("WeatherApp", "time"))
        self.labelTime_8.setText(_translate("WeatherApp", "temp"))
        self.labelTime_10.setText(_translate("WeatherApp", "temp"))
        self.labelTime_9.setText(_translate("WeatherApp", "time"))
        self.labelTime_12.setText(_translate("WeatherApp", "temp"))
        self.labelTime_11.setText(_translate("WeatherApp", "time"))
        self.labelTime_14.setText(_translate("WeatherApp", "temp"))
        self.labelTime_13.setText(_translate("WeatherApp", "time"))
        self.labelDay.setText(_translate("WeatherApp", "day"))
        self.label_2.setText(_translate("WeatherApp", "img"))
        self.labelMinTemp.setText(_translate("WeatherApp", "minTemp"))
        self.labelMaxTemp.setText(_translate("WeatherApp", "maxTemp"))
        self.labelDay_2.setText(_translate("WeatherApp", "day"))
        self.label_3.setText(_translate("WeatherApp", "img"))
        self.labelMinTemp_2.setText(_translate("WeatherApp", "minTemp"))
        self.labelMaxTemp_2.setText(_translate("WeatherApp", "maxTemp"))
        self.labelDay_3.setText(_translate("WeatherApp", "day"))
        self.label_4.setText(_translate("WeatherApp", "img"))
        self.labelMinTemp_3.setText(_translate("WeatherApp", "minTemp"))
        self.labelMaxTemp_3.setText(_translate("WeatherApp", "maxTemp"))
        self.label.setText(_translate("WeatherApp", "umiditate"))
        self.label_10.setText(_translate("WeatherApp", "valoare umiditate"))
        self.label_5.setText(_translate("WeatherApp", "presiune"))
        self.label_12.setText(_translate("WeatherApp", "valoare presiune"))
        self.label_6.setText(_translate("WeatherApp", "viteza vantului"))
        self.label_11.setText(_translate("WeatherApp", "valoare viteza vantului"))
        self.label_13.setText(_translate("WeatherApp", "vizibilitate"))
        self.label_7.setText(_translate("WeatherApp", "valoarea vizibilitatii"))
        self.label_8.setText(_translate("WeatherApp", "feels like temp"))
        self.label_14.setText(_translate("WeatherApp", "feels like temp value"))
        self.label_9.setText(_translate("WeatherApp", "procent nori"))
        self.label_15.setText(_translate("WeatherApp", "valoare procent nori"))
